version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumnes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Use Dockerfile for production
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./frontend/uploads:/app/frontend/uploads
    environment:
      - ENV=development
