version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENV=production
    volumes:
      - ./frontend/uploads:/root/frontend/uploads
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # For future HTTPS
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped