name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/virustotal-scanner"
        overwrite: true
        exclude : |
          .git/
          .guthub/
          *.md
          .gitignore

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Ensure Docker is running
          sudo systemctl start docker
          
          # Navigate to project directory
          cd ~/virustotal-scanner
          
          # Create required directories
          mkdir -p frontend/uploads
          chmod 755 frontend/uploads
          
          # Stop and remove existing containers
          docker-compose down || true
          
          # Pull latest images and rebuild
          docker-compose up --build -d
          
          # Verify containers are running
          docker ps
          
          # Verify Nginx configuration
          docker exec -it virustotal-scanner_nginx_1 nginx -t